### ISSUE TITLE
Old FAQ on LearnMore

### ISSUE THREAD

**Issue by Amaru8** [ciderapp/cider.sh#33]
https://github.com/ciderapp/cider.sh/blob/3d9d9e6f5149173087e5ea4ee1162e7b4d376c33/app/pages/learn-more.vue#L224

**Comment by Amaru8** [comment]
Also this: https://github.com/ciderapp/cider.sh/blob/3d9d9e6f5149173087e5ea4ee1162e7b4d376c33/app/pages/learn-more.vue#L230

**Comment by Amaru8** [comment]
I think after the merge of #32 , I will collect these old strings and change them in a pull together.

**Comment by yazninja** [comment]
sure, please do
